[build]
builder = "nixpacks"
buildCommand = """
  cd server
  npm install
  npm run build
"""

[deploy]
startCommand = """
  cd server
  node dist/index.js
"""
healthcheckPath = "/"
restartPolicyType = "ON_FAILURE" 