[phases.setup]
nixPkgs = ['python3', 'nodejs', 'curl', 'ffmpeg']
aptPkgs = ['python3', 'python3-pip', 'ffmpeg']

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  # Download standalone Python
  "curl -L https://github.com/indygreg/python-build-standalone/releases/download/20240107/cpython-3.11.7+20240107-x86_64-unknown-linux-gnu-install_only.tar.gz -o python.tar.gz",
  "tar xzf python.tar.gz",
  "mv python/install/* /usr/local/",
  "rm -rf python python.tar.gz",
  # Download and configure yt-dlp
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o yt-dlp",
  "chmod +x yt-dlp",
  # Verify installations
  "/usr/local/bin/python3 --version",
  "./yt-dlp --version"
]

[start]
cmd = "node dist/index.js"

[phases.setup.env]
PATH = "/usr/local/bin:/usr/bin:$PATH"
PYTHONHOME = "/usr/local" 