[phases.setup]
nixPkgs = ['nodejs', 'curl', 'ffmpeg']

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  # Download yt-dlp binary
  "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o yt-dlp",
  "chmod +x yt-dlp",
  "ls -la yt-dlp",  # Debug: verify file exists and is executable
  "./yt-dlp --version"  # Debug: verify it works
]

[start]
cmd = "node dist/index.js"

[phases.setup.env]
PATH = "/usr/local/bin:/usr/bin:$PATH" 