[build]
builder = "DOCKERFILE"
dockerfilePath = "."
watchPatterns = ["**"]

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
restartPolicyType = "ON_FAILURE"

[[deploy.envs]]
key = "NODE_ENV"
value = "production"

[[deploy.envs]]
key = "CORS_ORIGIN"
value = "https://twitch-batch-downloader.vercel.app" 